### ISSUE TITLE
マイコンのスリープ機能

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/SeeedJP_STM32F4#4]
https://github.com/SeeedJP/Wio_3G_for_Arduino/issues/4

**Comment by matsujirushi** [comment]
[dev-sleepブランチ](https://github.com/SeeedJP/SeeedJP_STM32F4/tree/dev-sleep)に実装中。

1. スリープ ... 実装済
2. EXTI割り込み ... 実装済
3. TIM割り込み ... 未着手

**Comment by matsujirushi** [comment]
masterにマージ。

**Comment by tanihito** [comment]
早速のご対応ありがとうございます！！

スリープ中のWio3Gの消費電流を測定したところ、約35mA消費しているようです（バッテリー駆動、LED等の電源Off状態）。少しコードを修正し、[ストップモード](https://os.mbed.com/users/EricLew/code/STM32L4xx_HAL_Driver/docs/tip/group__PWR__Exported__Functions__Group2.html#gacfca5f1062274423e08317c0a5a225fa)でも試してみましたが、依然15mA程度消費していました。

マイコン以外では、どの部分で電流を消費しているのでしょうか？また、更に消費電流を下げるために取りうる方法があれば教えていただけないでしょうか？よろしくお願いします。

**Comment by matsujirushi** [comment]
こちらはSeeedJP_STM32F4のIssueです。
ハードウェアに関しては、公開されている[回路図](https://github.com/SeeedJP/Wiki/blob/master/Wio_3G_for_Arduino/files/Wio_3G_vES.pdf)をご確認ください。

> 正確に測定していないためハッキリとしたことは分かりませんが、LPC11U35(IC2)やCHG LED(D4)、MP2617B(U6)の影響があるのでは？と思います。
> [こちら](https://technologicaladvance.blog.fc2.com/blog-entry-158.html)も参考になると思います。

**Comment by tanihito** [comment]
@matsujirushi 失礼しました。教えていただいたリンクを確認させていただきます。
TIM割り込みについても、もし可能でしたらご対応いただけると幸いです。
