### ISSUE TITLE
Wireを参照しているライブラリがコンパイル出来ない

### ISSUE THREAD

**Issue by intptr-t** [SeeedJP/SeeedJP_STM32F4#5]
ライブラリでWire.hにWireという名前でextern宣言されていることを前提としているライブラリがコンパイルできません。
**例**
https://github.com/intptr-t/Grove_SHT31_Temp_Humi_Sensor

WioCellularHardware.hに`extern TwoWire WireI2C;`で宣言され、WioCellularHardware.cppにて、実体が定義されているため、
一時的な回避策として、ライブラリの`Wire.h` に以下のように手を加えて対応しています。
```Cpp
extern TwoWire WireI2C;
#define Wire WireI2C
```

ライブラリに手を加えるのは望ましくないと考えております。
対応して頂くことは出来ないでしょうか。

**Comment by matsujirushi** [comment]
TBA

* for Wio 3G/Wio LTE M1/NB1(BG96)
  * SeeedJP_STM32F4 platform ... WireI2C, Wireの宣言なし。
  * Wio_cell_lib_for_Arduino library ... WireI2C(GROVE_I2C_CORE, GROVE_I2C_SDA_PIN, GROVE_I2C_SCL_PIN) / 25, 24
* for Wio LTE
  * stm32f4ArduinoCore platform ... Wire(SDA, SCL) / 25, 24
  * WioLTEforArduino library ... WireI2C, Wireの宣言なし。

**Comment by matsujirushi** [comment]
* for Wio 3G/Wio LTE M1/NB1(BG96)
  * SeeedJP_STM32F4 platform ... **Wire(GROVE_I2C_CORE, GROVE_I2C_SDA_PIN, GROVE_I2C_SCL_PIN) / 25, 24**
  * Wio_cell_lib_for_Arduino library ... WireI2C(GROVE_I2C_CORE, GROVE_I2C_SDA_PIN, GROVE_I2C_SCL_PIN) / 25, 24
* for Wio LTE
  * stm32f4ArduinoCore platform ... Wire(SDA, SCL) / 25, 24
  * WioLTEforArduino library ... WireI2C, Wireの宣言なし。

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/SeeedJP_STM32F4/commit/6c4c941055c195833d2ba287dbd3700c0d8d1a51

**Comment by matsujirushi** [comment]
@intptr-t masterにpushしました。
こちらで動作確認済みですが、念のため、そちらでも動作確認をお願い致します。

**Comment by intptr-t** [comment]
@matsujirushi ありがとうございます。
例で挙げた**Grove_SHT31_Temp_Humi_Sensor**と、スケッチ例のI2Cセンサー**grove-accelerometer**で期待する動作となることが確認できました。

**Comment by matsujirushi** [comment]
@intptr-t ご確認、ありがとうございました。

Released.
https://github.com/SeeedJP/SeeedJP_STM32F4/commit/507276357a5d33657e23407976ab2d6e410b90d8
