### ISSUE TITLE
constrainが未定義でライブラリがコンパイルできない

### ISSUE THREAD

**Issue by intptr-t** [SeeedJP/SeeedJP_STM32F4#6]
"Arduino.h"をインクルードすることで、取り込まれる[constrain](https://www.arduino.cc/reference/en/language/functions/math/constrain/)機能が実装されていないため、
[Grove_ChainableLED](https://github.com/Seeed-Studio/Grove_ChainableLED)がコンパイルできません。
対応して頂くことは出来ますでしょうか。

**エラーログ**
```
ChainableLED-1.2/ChainableLED.cpp:138:28: error: 'constrain' was not declared in this scope
     constrain(hue, 0.0, 1.0);
```
-------

他 Math 機能横にらみ結果、以下の機能が内容が搭載されていないようです。

- [max](https://www.arduino.cc/reference/en/language/functions/math/max/) (※std::maxではなく、グローバルのmax)
- [min](https://www.arduino.cc/reference/en/language/functions/math/min/) (※std::minではなく、グローバルのmin)
- [sq](https://www.arduino.cc/reference/en/language/functions/math/sq/)

(参照: https://www.arduino.cc/reference/en/#functions)

I/Oなどの制約を除いて、どこまでArduino互換を目指すものなのでしょうか？

**Comment by matsujirushi** [comment]
> I/Oなどの制約を除いて、どこまでArduino互換を目指すものなのでしょうか？

都度、弊社判断になります。

なお、Arduino IDE向けPlatformを一新する予定です。既存のPlatformで、TFカードが使えないとか他社ライブラリがコンパイル通らない、、、といった問題に対処するためです。

# 参考

* [WioLTEシリーズの製品ラインナップと開発プラットフォーム事情](https://qiita.com/matsujirushi/items/fa92b9cef36b3b3ba3c4)
* [新しいPlatform](https://github.com/SeeedJP/Arduino_Core_STM32)
